version: "3"
services:
  frontend:
    container_name: client
    build: ./frontend
    ports:
      - "8080:3000"
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "4000:4000"
